name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        uses: asdf-vm/actions/install@v3
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: bun test --coverage --coverage-reporter=lcov
      - name: Save coverage report
        uses: actions/cache@v4
        with:
          path: coverage
          key: ${{ runner.os }}-coverage
  sonarcloud:
    needs: test
    name: SonarQube Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Restore cached coverage report
        uses: actions/cache/restore@v4
        with:
          path: coverage
          key: ${{ runner.os }}-coverage
      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: -X
